#!/usr/bin/env python3
"""ledger.md を生成する。出典とクレームの正はこのファイル。"""
S = [
# id, name, url, tier, sq
("S-01","Gruber, A Translation Approach to Portable Ontology Specifications (KSL 92-71 / Knowledge Acquisition 5(2), 1993)","https://tomgruber.org/writing/ontolingua-kaj-1993.pdf","T1","SQ1"),
("S-02","Studer, Benjamins, Fensel, Knowledge Engineering: Principles and Methods (preprint; DKE 25, 1998)","https://publikationen.bibliothek.kit.edu/189497/3003","T1","SQ1"),
("S-03","Lenat, CYC: A Large-Scale Investment in Knowledge Infrastructure (CACM 38(11), 1995; mirror)","https://papers.baulab.info/papers/knowledge/Lenat-1995.pdf","T1","SQ1"),
("S-04","Berners-Lee, Hendler, Lassila, The Semantic Web (Scientific American, May 2001)","https://www.scientificamerican.com/article/the-semantic-web/","T1","SQ1"),
("S-05","Guarino, Formal Ontology and Information Systems (FOIS'98)","https://www.loa.istc.cnr.it/old/Papers/FOIS98.pdf","T1","SQ1"),
("S-06","W3C, OWL Web Ontology Language Overview (REC 2004-02-10)","https://www.w3.org/TR/2004/REC-owl-features-20040210/","T1","SQ1/SQ2"),
("S-07","W3C, RDF Model and Syntax Specification (REC 1999-02-22)","https://www.w3.org/TR/1999/REC-rdf-syntax-19990222/","T1","SQ2"),
("S-08","W3C, RDF 1.1 Concepts and Abstract Syntax (REC 2014-02-25)","https://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/","T1","SQ2"),
("S-09","W3C, RDF 1.2 Concepts and Abstract Data Model","https://www.w3.org/TR/rdf12-concepts/","T1","SQ2"),
("S-10","W3C, RDF Schema 1.1 (REC 2014-02-25)","https://www.w3.org/TR/2014/REC-rdf-schema-20140225/","T1","SQ2"),
("S-11","W3C, OWL 2 Document Overview (Second Edition) (REC 2012-12-11)","https://www.w3.org/TR/2012/REC-owl2-overview-20121211/","T1","SQ2"),
("S-12","W3C, SKOS Reference (REC 2009-08-18)","https://www.w3.org/TR/2009/REC-skos-reference-20090818/","T1","SQ2"),
("S-13","W3C, SPARQL Query Language for RDF (REC 2008-01-15)","https://www.w3.org/TR/2008/REC-rdf-sparql-query-20080115/","T1","SQ2"),
("S-14","W3C, SPARQL 1.1 Overview (REC 2013-03-21)","https://www.w3.org/TR/2013/REC-sparql11-overview-20130321/","T1","SQ2"),
("S-15","W3C, Shapes Constraint Language (SHACL) (REC 2017-07-20)","https://www.w3.org/TR/2017/REC-shacl-20170720/","T1","SQ2"),
("S-16","W3C, JSON-LD 1.0 (REC 2014-01-16)","https://www.w3.org/TR/2014/REC-json-ld-20140116/","T1","SQ2"),
("S-17","W3C, JSON-LD 1.1 (REC 2020-07-16)","https://www.w3.org/TR/2020/REC-json-ld11-20200716/","T1","SQ2"),
("S-18","W3C Semantic Web Activity","https://www.w3.org/2001/sw/","T1","SQ2"),
("S-19","Crossref: Codd 1970 (doi 10.1145/362384.362685)","https://api.crossref.org/works/10.1145/362384.362685","T1","SQ3"),
("S-20","Crossref: Chen 1976 (doi 10.1145/320434.320440)","https://api.crossref.org/works/10.1145/320434.320440","T1","SQ3"),
("S-21","DCMI History","https://www.dublincore.org/about/history/","T1","SQ3"),
("S-22","DCMI Metadata Terms","https://www.dublincore.org/specifications/dublin-core/dcmi-terms/","T1","SQ3"),
("S-23","OMG, Meta Object Facility (MOF) 2.5.1","https://www.omg.org/spec/MOF/2.5.1/","T1","SQ3"),
("S-24","W3C, XML Schema Part 1: Structures (REC 2001-05-02)","https://www.w3.org/TR/2001/REC-xmlschema-1-20010502/","T1","SQ3"),
("S-25","json-schema.org, What is JSON Schema?","https://json-schema.org/overview/what-is-jsonschema","T1","SQ3"),
("S-26","Schema.org, About","https://schema.org/docs/about.html","T1","SQ3"),
("S-27","W3C, DCAT (REC 2014-01-16)","https://www.w3.org/TR/2014/REC-vocab-dcat-20140116/","T1","SQ3"),
("S-28","W3C, DCAT Version 2","https://www.w3.org/TR/vocab-dcat-2/","T1","SQ3"),
("S-29","W3C, DCAT Version 3","https://www.w3.org/TR/vocab-dcat-3/","T1","SQ3"),
("S-30","Snowflake press release 2025-09-23 (Yahoo Finance copy)","https://finance.yahoo.com/news/snowflake-salesforce-dbt-labs-more-130100051.html","T2","SQ4"),
("S-31","Snowflake blog, OSI Updates: Specification Live (2026-01-27)","https://www.snowflake.com/en/blog/open-semantic-interchanges-specs-finalized/","T2","SQ4"),
("S-32","Apache Ossie, OSI Community Update (2026-04-28)","https://ossie.apache.org/updates/osi-april-2026-community-update/","T2","SQ4"),
("S-33","Apache Ossie (Incubating): The New Name for OSI (2026-07-10)","https://ossie.apache.org/updates/ossie-enters-apache-incubator/","T2","SQ4"),
("S-34","Apache Ossie README (GitHub)","https://raw.githubusercontent.com/apache/ossie/main/README.md","T1","SQ4"),
("S-35","Databricks blog, Redefining the Semantics Data Layer (2026-04-02)","https://www.databricks.com/blog/redefining-semantics-data-layer-future-bi-and-ai","T2","SQ4"),
("S-36","dbt Labs blog, Open Sourcing MetricFlow (2025-10-14)","https://www.getdbt.com/blog/dbt-labs-affirms-commitment-to-open-semantic-interchange-by-open-sourcing-metricflow","T2","SQ4"),
("S-37","Chris Webb, Power BI Datasets Renamed To Semantic Models (2023-11-18)","https://blog.crossjoin.co.uk/2023/11/18/thoughts-on-power-bi-datasets-being-renamed-to-semantic-models/","T3","SQ4"),
("S-38","Google Cloud blog, Opening up the Looker semantic layer (2024-08-15)","https://cloud.google.com/blog/products/business-intelligence/opening-up-the-looker-semantic-layer","T2","SQ4"),
("S-39","AtScale glossary, Semantic Layer","https://www.atscale.com/glossary/semantic-layer/","T2","SQ4"),
("S-40","Google blog, Introducing the Knowledge Graph: things, not strings (2012-05-16)","https://blog.google/products/search/introducing-knowledge-graph-things-not/","T2","SQ5"),
("S-41","Wikidata:Introduction","https://www.wikidata.org/wiki/Wikidata:Introduction","T2","SQ5"),
("S-42","Palantir Foundry docs, Ontology overview","https://www.palantir.com/docs/foundry/ontology/overview/","T2","SQ5"),
("S-43","ISO/IEC 39075:2024 GQL (IEC webstore)","https://webstore.iec.ch/publication/94107","T1","SQ5"),
("S-44","Neo4j blog, RDF vs. Property Graphs (2024-06-04)","https://neo4j.com/blog/knowledge-graph/rdf-vs-property-graphs-knowledge-graphs/","T2","SQ5"),
("S-45","Microsoft Research blog, GraphRAG (2024-02-13)","https://www.microsoft.com/en-us/research/blog/graphrag-unlocking-llm-discovery-on-narrative-private-data/","T2","SQ5"),
("S-46","Hogan et al., Knowledge Graphs (arXiv 2003.02320; ACM CSUR 54(4), 2021)","https://arxiv.org/abs/2003.02320","T1","SQ5"),
("S-47","ISO/IEC 21838-2:2021 BFO (IEC webstore)","https://webstore.iec.ch/publication/72703","T1","SQ5/SQ6"),
("S-48","Common Core Ontologies README (GitHub)","https://raw.githubusercontent.com/CommonCoreOntology/CommonCoreOntologies/develop/README.md","T1","SQ5"),
("S-49","NIEMOpen, NIEM, a new Open Project 18 years in the making (2023-02-17)","https://niemopen.org/news/niem-a-new-open-project-18-years-in-the-making/","T2","SQ5"),
("S-50","EDM Council, FIBO","https://spec.edmcouncil.org/fibo/","T1","SQ6"),
("S-51","Gene Ontology documentation","https://geneontology.org/docs/ontology-documentation/","T1","SQ6"),
("S-52","SNOMED International, What is SNOMED CT","https://www.snomed.org/what-is-snomed-ct","T1","SQ6"),
("S-53","HL7 FHIR Overview","https://hl7.org/fhir/","T1","SQ6"),
("S-54","CFIHOS (JIP36)","https://www.jip36-cfihos.org/","T1","SQ6"),
("S-55","IDTA home","https://industrialdigitaltwin.org/en/","T1","SQ6"),
("S-56","ECLASS introduction","https://eclass.eu/en/eclass-standard/introduction","T1","SQ6"),
("S-57","OAGi, Industrial Ontologies Foundry","https://oagi.org/pages/industrial-ontologies","T1","SQ6"),
("S-58","OBO Foundry","https://obofoundry.org/","T1","SQ6"),
("S-59","共通語彙基盤 (IMI)","https://imi.go.jp/","T1","SQ6"),
("S-60","IDS Information Model README (GitHub)","https://raw.githubusercontent.com/International-Data-Spaces-Association/InformationModel/develop/README.md","T1","SQ7"),
("S-61","GitHub API: IDS InformationModel repo metadata","https://api.github.com/repos/International-Data-Spaces-Association/InformationModel","T1","SQ7"),
("S-62","Dataspace Protocol 2025-1, Common (source md)","https://raw.githubusercontent.com/eclipse-dataspace-protocol-base/DataspaceProtocol/2025-1/specifications/common/common.protocol.md","T1","SQ7"),
("S-63","Dataspace Protocol 2025-1, Catalog Protocol (source md)","https://raw.githubusercontent.com/eclipse-dataspace-protocol-base/DataspaceProtocol/2025-1/specifications/catalog/catalog.protocol.md","T1","SQ7"),
("S-64","Eclipse Foundation newsroom, EDWG advances two open protocols toward ISO/IEC standardisation (2025-12-02)","https://newsroom.eclipse.org/node/43194","T1","SQ7"),
("S-65","European Commission, New European Interoperability Framework (2017, brochure of COM(2017) 134 Annex 2)","https://ec.europa.eu/isa2/sites/default/files/eif_brochure_final.pdf","T1","SQ7"),
("S-66","DSSC Blueprint v2.0, Data Models","https://archive.dssc.eu/space/BVE2/1071255252.md","T1","SQ7"),
("S-67","ODS-RAM 3. レイヤ (ODS 公式 GitBook)","https://open-dataspaces.gitbook.io/ods-docs/jp/ods-ram/03-layers","T2","SQ7"),
("S-68","IPA プレス発表 2026-04-01 Open Data Spaces の成果物を公開","https://www.ipa.go.jp/pressrelease/2026/press20260401.html","T1","SQ7"),
("S-69","Catena-X CX-0003 SAMM Aspect Meta Model","https://catenax-ev.github.io/docs/standards/CX-0003-SAMMSemanticAspectMetaModel","T1","SQ7"),
("S-70","Eclipse ESMF, SAMM Specification","https://eclipse-esmf.github.io/samm-specification/snapshot/index.html","T1","SQ7"),
("S-71","SEMIC, DCAT-AP 3.0.1","https://semiceu.github.io/DCAT-AP/releases/3.0.1/","T1","SQ7"),
("S-72","Gaia-X Architecture Document 24.04, Conceptual model","https://docs.gaia-x.eu/technical-committee/architecture-document/24.04/gx_conceptual_model/","T1","SQ7"),
("S-73","Crossref: Ashburner et al. 2000, Gene Ontology (doi 10.1038/75556)","https://api.crossref.org/works/10.1038/75556","T1","SQ6"),
("S-74","Crossref: Brachman & Schmolze 1985, KL-ONE (doi 10.1207/s15516709cog0902_1)","https://api.crossref.org/works/10.1207/s15516709cog0902_1","T1","SQ1"),
("S-75","Apache Incubator, Ossie Project Incubation Status","https://incubator.apache.org/projects/ossie.html","T1","FC"),
("S-76","Microsoft Learn, Datasets renamed to semantic models","https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-rename","T2","FC"),
("S-77","IEC 63278-1:2023 Asset Administration Shell for industrial applications, Part 1 (IEC webstore)","https://webstore.iec.ch/en/publication/65628","T1","FC"),
("S-78","Google Search Central Blog, Introducing schema.org (2011-06-02)","https://developers.google.com/search/blog/2011/06/introducing-schemaorg-search-engines","T2","FC"),
("S-79","Institute for Standardization of Serbia, ISO/IEC DIS 26450 project record (ISO status mirror)","https://iss.rs/en/project/show/iso:proj:93502","T3","FC"),
("S-80","IDS Information Model, Contract.ttl (GitHub)","https://raw.githubusercontent.com/International-Data-Spaces-Association/InformationModel/develop/model/contract/Contract.ttl","T1","FC"),
("S-81","IDS Information Model, Resource.ttl (GitHub)","https://raw.githubusercontent.com/International-Data-Spaces-Association/InformationModel/develop/model/content/Resource.ttl","T1","FC"),
("S-82","ODP メタデータエクスチェンジ(L4) Protocol（ODS 公式 GitBook）","https://open-dataspaces.gitbook.io/ods-docs/jp/odp/fandamentarupurotokoru/metadtaekusuchenjil4/protocol.md","T2","追補"),
("S-83","Apache Ossie, Core Metadata Specification (version 0.2.0.dev0)","https://raw.githubusercontent.com/apache/ossie/main/core-spec/spec.md","T1","追補"),
("S-84","Apache Ossie, Ontology Specification (version 0.2.0.dev0)","https://raw.githubusercontent.com/apache/ossie/main/ontology/ontology.md","T1","追補"),
("S-85","ODS-RAM 用語集（ODS 公式 GitBook）","https://open-dataspaces.gitbook.io/ods-docs/jp/ods-ram/glossary.md","T2","追補"),
("S-86","デジタル庁, 政府相互運用性フレームワーク（GIF）概要資料（2025-03-25）","https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/c1bdb4a2-850f-48ec-a938-a8369f820ac1/d47def21/20250325_policies_development_management_outline_03.pdf","T1","追補"),
("S-87","デジタル庁, 政府相互運用性フレームワーク（GIF）","https://www.digital.go.jp/policies/data_strategy_government_interoperability_framework","T1","追補"),
("S-88","IPA, データの相互運用性向上のためのガイド 第二版（2021-03-25）","https://www.ipa.go.jp/digital/data/ug65p90000001lp7-att/000089404.pdf","T1","追補"),
("S-89","open-dataspaces/SDK-for-semantics, ods.ttl（ODS Ontology）","https://raw.githubusercontent.com/open-dataspaces/SDK-for-semantics/main/Documents/WebServiceAspectModel/ods.ttl","T1","追補"),
("S-90","open-dataspaces/SDK-for-semantics, README","https://raw.githubusercontent.com/open-dataspaces/SDK-for-semantics/main/README.md","T1","追補"),
("S-91","open-dataspaces/L4-sparql-server-sample, README","https://raw.githubusercontent.com/open-dataspaces/L4-sparql-server-sample/main/README.md","T1","追補"),
("S-92","open-dataspaces/L4-sparql-server-sample, ontology/uasl-core-2026-01-06.ttl","https://raw.githubusercontent.com/open-dataspaces/L4-sparql-server-sample/main/ontology/uasl-core-2026-01-06.ttl","T1","追補"),
("S-93","open-dataspaces/L4-uasl-chat-server, README","https://raw.githubusercontent.com/open-dataspaces/L4-uasl-chat-server/main/README.md","T1","追補"),
("S-94","open-dataspaces, organization profile README","https://raw.githubusercontent.com/open-dataspaces/.github/main/profile/README.md","T1","追補"),
("S-95","open-dataspaces/L4-crawler-service, README","https://raw.githubusercontent.com/open-dataspaces/L4-crawler-service/main/README.md","T1","追補"),
("S-96","Palantir Foundry docs, Required properties","https://www.palantir.com/docs/foundry/object-link-types/required-properties/","T2","追補"),
("S-97","Palantir Foundry docs, Value types","https://www.palantir.com/docs/foundry/object-link-types/value-types-overview/","T2","追補"),
("S-98","Palantir Foundry docs, Multi-datasource object types (MDOs)","https://www.palantir.com/docs/foundry/object-permissioning/multi-datasource-objects/","T2","追補"),
("S-99","Palantir Foundry docs, Shared properties","https://www.palantir.com/docs/foundry/object-link-types/shared-property-overview/","T2","追補"),
("S-100","Palantir Foundry docs, Interfaces","https://www.palantir.com/docs/foundry/interfaces/interface-overview/","T2","追補"),
("S-101","Palantir Foundry docs, Derived properties","https://www.palantir.com/docs/foundry/ontology/derived-properties/","T2","追補"),
("S-102","Palantir Foundry docs, Functions","https://www.palantir.com/docs/foundry/functions/overview/","T2","追補"),
("S-103","Palantir Foundry docs, Types reference","https://www.palantir.com/docs/foundry/object-link-types/type-reference/","T2","追補"),
("S-104","Palantir Foundry docs, The Ontology system","https://www.palantir.com/docs/foundry/architecture-center/ontology-system/","T2","追補"),
("S-105","Palantir Foundry docs, Export, edit, and import an Ontology","https://www.palantir.com/docs/foundry/ontology-manager/export-import/","T2","追補"),
("S-106","Apache Ossie, Roadmap","https://raw.githubusercontent.com/apache/ossie/main/ROADMAP.md","T1","追補"),
("S-107","US Patent 5,555,403, Relational database access system using semantically dynamic objects (Business Objects)","https://patents.google.com/patent/US5555403A/en","T1","追補"),
("S-108","Benn Stancil, The missing piece of the modern data stack (2021-04-22)","https://benn.substack.com/p/metrics-layer","T3","追補"),
("S-109","Aidan Hogan, The Semantic Web: Two Decades On (Semantic Web journal, 2020)","https://semantic-web-journal.net/system/files/swj2303.pdf","T1","追補"),
("S-110","George Anadiotis, Universal semantic layer: Going meta on data, functionality, governance, and semantics","https://linkeddataorchestration.substack.com/p/universal-semantic-layer-going-meta","T3","追補"),
("S-111","dbt Labs docs, dbt Semantic Layer","https://docs.getdbt.com/docs/use-dbt-semantic-layer/dbt-sl","T2","追補"),
("S-112","IPA, Why Open Dataspaces: 設計思想とアーキテクチャパラダイム（2026-04-01）","https://www.ipa.go.jp/digital/architecture/documents/rcu1hd000000chgw-att/WhyOpenDataspaces_jp.pdf","T1","追補"),
("S-113","Dataspace Protocol README（tag 2025-1）","https://raw.githubusercontent.com/eclipse-dataspace-protocol-base/DataspaceProtocol/2025-1/README.md","T1","追補"),
("S-114","IDS-RAM 4.0, Information Layer","https://raw.githubusercontent.com/International-Data-Spaces-Association/IDS-RAM_4_0/main/documentation/3_Layers_of_the_Reference_Architecture_Model/3_3_Information_Layer/3_3_InformationLayer.md","T1","追補"),
("S-115","Dataspace Protocol 2025-1, dspace.jsonld（JSON-LD コンテキスト）","https://raw.githubusercontent.com/eclipse-dataspace-protocol-base/DataspaceProtocol/2025-1/artifacts/src/main/resources/context/dspace.jsonld","T1","追補"),
("S-116","IDSA ids-specification, Dataspace Protocol 2024-1, common.protocol.md","https://raw.githubusercontent.com/International-Data-Spaces-Association/ids-specification/2024-1/common/common.protocol.md","T1","追補"),
("S-117","IDSA ids-specification README（tag v0.8, Working Draft 2023-02-01）","https://raw.githubusercontent.com/International-Data-Spaces-Association/ids-specification/v0.8/README.md","T1","追補"),
("S-118","DataspaceProtocol issue #25, Proposal: Adopt JSON Schema for normative serialization（2024-09-16）","https://api.github.com/repos/eclipse-dataspace-protocol-base/DataspaceProtocol/issues/25","T2","追補"),
("S-119","Ogden & Richards, The Meaning of Meaning (1923; Internet Archive の OCR テキスト)","https://archive.org/download/bwb_W9-COP-402/bwb_W9-COP-402_djvu.txt","T1","追補"),
("S-120","Uschold & Gruninger, Ontologies and Semantics for Seamless Connectivity (SIGMOD Record 33(4), 2004)","https://sigmodrecord.org/?smd_process_download=1&download_id=5095","T1","追補"),
("S-121","McGuinness, Ontologies Come of Age (Spinning the Semantic Web, MIT Press, 2003; Wayback 収録)","https://web.archive.org/web/20201129074402/http://www.ksl.stanford.edu/people/dlm/papers/ontologies-come-of-age-mit-press-%28with-citation%29.htm","T1","追補"),
("S-122","Pras & Schoenwaelder, RFC 3444: On the Difference between Information Models and Data Models (IETF, 2003-01)","https://www.rfc-editor.org/rfc/rfc3444.txt","T1","追補"),
("S-123","W3C, Ontologies（Standards > Semantic Web。Wayback 2013 収録）","https://web.archive.org/web/2013/http://www.w3.org/standards/semanticweb/ontology","T1","追補"),
("S-124","Wikimedia Commons, File:Datamodel in Wikidata.svg（Charlie Kritschmar (WMDE)、CC0）","https://commons.wikimedia.org/wiki/File:Datamodel_in_Wikidata.svg","T2","追補"),
("S-125","Palantir Foundry docs, Core concepts","https://www.palantir.com/docs/foundry/ontology/core-concepts/","T2","追補"),
("S-126","IDSA ids-specification, Dataspace Protocol 2024-1, catalog.protocol.md","https://raw.githubusercontent.com/International-Data-Spaces-Association/ids-specification/2024-1/catalog/catalog.protocol.md","T1","追補"),
("S-127","Model Context Protocol, What is the Model Context Protocol (MCP)?","https://modelcontextprotocol.io/docs/getting-started/intro","T2","追補"),
("S-128","Palantir Foundry docs, Property metadata","https://www.palantir.com/docs/foundry/object-link-types/property-metadata/","T2","追補"),
("S-129","Open Knowledge Format (OKF) specification, Version 0.2 (GoogleCloudPlatform/open-knowledge-format, SPEC.md)","https://raw.githubusercontent.com/GoogleCloudPlatform/open-knowledge-format/main/SPEC.md","T2","追補"),
("S-130","Open Knowledge Format (OKF), README (GoogleCloudPlatform/open-knowledge-format)","https://raw.githubusercontent.com/GoogleCloudPlatform/open-knowledge-format/main/README.md","T2","追補"),
("S-131","Google Cloud Blog, Introducing the Open Knowledge Format (2026-06-12)","https://cloud.google.com/blog/products/data-analytics/how-the-open-knowledge-format-can-improve-data-sharing/","T2","追補"),
("S-132","Google Cloud Blog, Open Knowledge format v0.2 tackles agentic trust (2026-07-24)","https://cloud.google.com/blog/products/data-analytics/okf-v0-2-adds-trust-signals","T2","追補"),
("S-133","W3C, Data on the Web Best Practices (W3C Recommendation, 2017-01-31)","https://www.w3.org/TR/dwbp/","T1","追補"),
]
C = [
# id, claim, source, span, kind
("C-01","Gruber は 1993 年の論文でオントロジーを「概念化の明示的な仕様」と定義した","S-01","An ontology is an explicit specification of a conceptualization.","verifiable"),
("C-02","Studer らは、先行する定義に基づき、オントロジーを「共有された概念化の、形式的で明示的な仕様」とする定義を示した","S-02","the essence of an ontology is based on the related definitions in ([74], [22]): An ontology is a formal, explicit specification of a shared conceptualisation.","verifiable"),
("C-03","Lenat は Cyc の構築を 1984 年に始めたと述べている","S-03","embarked on that task in 1984","verifiable"),
("C-04","論文「The Semantic Web」は Scientific American の 2001 年 5 月号に掲載された","S-04","Scientific American Magazine Vol. 284 No. 5 (May 2001)","verifiable"),
("C-05","Guarino は AI におけるオントロジーを、語彙とその意味に関する明示的な前提からなる工学的な成果物だと説明した","S-05","an ontology refers to an engineering artifact, constituted by a specific vocabulary used to describe a certain reality, plus a set of explicit assumptions regarding the intended meaning of the vocabulary words","verifiable"),
("C-06","Guarino は上位オントロジーを、特定の問題や領域に依存しない非常に一般的な概念を記述するものとした","S-05","Top-level ontologies describe very general concepts like space, time, matter, object, event, action, etc., which are independent of a particular problem or domain","verifiable"),
("C-07","OWL DL の名は記述論理との対応に由来し、記述論理は OWL の形式的基礎である","S-06","OWL DL is so named due to its correspondence with description logics, a field of research that has studied the logics that form the formal foundation of OWL.","verifiable"),
("C-08","KL-ONE の概説論文は 1985 年に Cognitive Science 誌に掲載された","S-74","\"container-title\":[\"Cognitive Science\"]","verifiable"),
("C-09","1999 年 2 月 22 日付の RDF 仕様は、RDF をメタデータ処理の基盤と位置づけた","S-07","Resource Description Framework (RDF) is a foundation for processing metadata","verifiable"),
("C-10","RDF 1.1 は 2014 年 2 月 25 日に W3C 勧告となった","S-08","W3C Recommendation 25 February 2014","verifiable"),
("C-11","RDF は Web 上で情報を表現するための枠組みである","S-08","The Resource Description Framework (RDF) is a framework for representing information in the Web.","verifiable"),
("C-12","RDF 1.2 は 2026 年 4 月 7 日付で勧告候補スナップショットの段階にある","S-09","W3C Candidate Recommendation Snapshot 07 April 2026","verifiable"),
("C-13","RDF Schema は RDF データのためのデータモデリング語彙を提供する","S-10","RDF Schema provides a data-modelling vocabulary for RDF data.","verifiable"),
("C-14","OWL は 2004 年 2 月 10 日に W3C 勧告となった","S-06","W3C Recommendation 10 February 2004","verifiable"),
("C-15","OWL 2 第 2 版は 2012 年 12 月 11 日に W3C 勧告となり、形式的に定義された意味を持つオントロジー言語である","S-11","The OWL 2 Web Ontology Language, informally OWL 2, is an ontology language for the Semantic Web with formally defined meaning.","verifiable"),
("C-16","SKOS は 2009 年 8 月 18 日に W3C 勧告となり、知識組織化体系を共有しリンクするための共通データモデルである","S-12","a common data model for sharing and linking knowledge organization systems via the Web","verifiable"),
("C-17","SPARQL は 2008 年 1 月 15 日に W3C 勧告となった","S-13","W3C Recommendation 15 January 2008","verifiable"),
("C-18","SPARQL 1.1 は 2013 年 3 月 21 日に W3C 勧告となった","S-14","W3C Recommendation 21 March 2013","verifiable"),
("C-19","SHACL は 2017 年 7 月 20 日に W3C 勧告となり、RDF グラフを条件の集合に照らして検証する言語である","S-15","a language for validating RDF graphs against a set of conditions","verifiable"),
("C-20","JSON-LD は Linked Data を直列化する JSON ベースの形式である","S-16","JSON-LD, a JSON-based format to serialize Linked Data","verifiable"),
("C-21","JSON-LD 1.1 は 2020 年 7 月 16 日に W3C 勧告となった","S-17","W3C Recommendation 16 July 2020","verifiable"),
("C-22","W3C はセマンティックウェブを、アプリケーション・企業・コミュニティの境界を越えてデータを共有し再利用できる共通の枠組みと説明した","S-18","The Semantic Web provides a common framework that allows data to be shared and reused across application, enterprise, and community boundaries.","verifiable"),
("C-23","Codd の関係モデル論文は 1970 年 6 月に Communications of the ACM に掲載された","S-19","\"container-title\":[\"Communications of the ACM\"]","verifiable"),
("C-24","Chen の実体関連モデル論文は 1976 年 3 月に ACM Transactions on Database Systems に掲載された","S-20","\"container-title\":[\"ACM Transactions on Database Systems\"]","verifiable"),
("C-25","ダブリンコアの歴史は、Web 資源のための中核的な意味の集合を議論した OCLC/NCSA メタデータワークショップに始まる","S-21","called simply the \"OCLC/NCSA Metadata Workshop\", more than 50 people discussed how a core set of semantics for Web-based resources would be extremely useful","verifiable"),
("C-26","ダブリンコアは ISO 15836 として 2003 年に初めて発行された","S-22","ISO 15836, which was published first in 2003 and last revised in 2017 as ISO 15836-1:2017","verifiable"),
("C-27","MOF は OMG のモデル駆動アーキテクチャ言語群におけるメタモデル定義の基礎である","S-23","provides the basis for metamodel definition in the OMG family of MDA languages","verifiable"),
("C-28","XML Schema は 2001 年 5 月 2 日に W3C 勧告となった","S-24","W3C Recommendation 2 May 2001","verifiable"),
("C-29","JSON Schema は JSON データの構造と制約を定義する宣言的な言語である","S-25","JSON Schema is a declarative language for defining structure and constraints for JSON data.","verifiable"),
("C-30","Schema.org の創設企業は Google、Microsoft、Yahoo、Yandex である","S-26","the founding companies (Google, Microsoft, Yahoo and Yandex)","verifiable"),
("C-31","DCAT は 2014 年 1 月 16 日に W3C 勧告となった","S-27","W3C Recommendation 16 January 2014","verifiable"),
("C-32","DCAT は Web 上で公開されるデータカタログ間の相互運用性を高めるための RDF 語彙である","S-29","DCAT is an RDF vocabulary designed to facilitate interoperability between data catalogs published on the Web.","verifiable"),
("C-33","OSI は 2025 年 9 月 23 日に Snowflake が Salesforce、BlackRock、dbt Labs、RelationalAI 等とともに発表したオープンソースの取り組みである","S-30","Snowflake (NYSE: SNOW), the AI Data Cloud company in partnership with leading industry partners and ecosystem vendors, including Salesforce, BlackRock, dbt Labs, and RelationalAI, announced a bold commitment to lead the Open Semantic Interchange (OSI), a new open source initiative","verifiable"),
("C-34","OSI 仕様の最初の版は Apache 2 ライセンスの Git リポジトリで公開された","S-31","The first version of the OSI specification is now available via an Apache 2 licensed Git repository","verifiable"),
("C-35","2026 年 1 月の更新で Databricks、AtScale、Qlik 等が OSI ワーキンググループに加わった","S-31","added the following organizations to the OSI working group: AtScale, Coalesce, Collate, Credible, Databricks, JetBrains, Lightdash and Qlik","verifiable"),
("C-36","2026 年 4 月の OSI コミュニティ更新は、新たなワーキンググループ参加者を列挙している","S-32","New working group participants include:","verifiable"),
("C-37","OSI は Apache Incubator に受け入れられ、Apache Ossie (Incubating) に改称された","S-33","accepted into the Apache Incubator under a new name: Apache Ossie (Incubating)","verifiable"),
("C-38","Ossie は自らをセマンティックレイヤとオントロジーの両方のためのオープン仕様と位置づけている","S-33","Ossie is an open specification for both semantic layer and ontology.","verifiable"),
("C-39","Ossie の仕様は JSON および YAML ベースである","S-34","JSON- and YAML-based specification","verifiable"),
("C-40","Databricks は 2026 年 4 月に Unity Catalog Business Semantics の一般提供を発表した","S-35","Unity Catalog Business Semantics is now GA","verifiable"),
("C-41","dbt Labs は MetricFlow を Apache 2.0 ライセンスでオープンソース化すると発表した","S-36","it is open sourcing MetricFlow with an Apache 2.0 licence","verifiable"),
("C-42","Power BI の「データセット」は 2023 年 11 月に「セマンティックモデル」へ改称された","S-37","Power BI datasets have been renamed: they are now semantic models","verifiable"),
("C-43","Google は Looker を、指標を一度定義してどこでも使えるセマンティックモデルを中核とする設計だと説明している","S-38","semantic model at its core that lets you define metrics once and use them everywhere","verifiable"),
("C-44","AtScale はセマンティックレイヤを、データウェアハウスとそれにアクセスするツールの間に位置するソフトウェア層と定義している","S-39","A semantic layer is a software layer that sits between your data warehouse and the tools that access it.","verifiable"),
("C-45","Google は 2012 年 5 月 16 日付の記事「Introducing the Knowledge Graph: things, not strings」でナレッジグラフを紹介した","S-40","things, not strings","verifiable"),
("C-46","Wikidata は自由で協働的な多言語の知識ベースである","S-41","a free, collaborative, multilingual, secondary knowledge base","verifiable"),
("C-47","Palantir は自社の Ontology を組織の運用レイヤと定義している","S-42","The Palantir Ontology is an operational layer for the organization.","verifiable"),
("C-48","Palantir の Ontology は意味要素（オブジェクト、プロパティ、リンク）と動的要素（アクション、関数、動的セキュリティ）の両方を含む","S-42","containing both the semantic elements (objects, properties, links) and kinetic elements (actions, functions, dynamic security)","verifiable"),
("C-49","ISO/IEC 39075:2024 (GQL) はプロパティグラフのデータ構造と基本操作を定義する","S-43","This document defines data structures and basic operations on property graphs.","verifiable"),
("C-50","Neo4j は、プロパティグラフはデータ交換形式ではなくデータベースモデルとして設計されたと説明している","S-44","Property graphs were designed as a database model (rather than data exchange format) for applications and analytics.","verifiable"),
("C-51","Microsoft Research は 2024 年 2 月 13 日付のブログ記事で GraphRAG を紹介した","S-45","GraphRAG","verifiable"),
("C-52","知識グラフは、多様で動的かつ大規模なデータ集合を活用する場面で産学の注目を集めている","S-46","knowledge graphs, which have recently garnered significant attention from both industry and academia in scenarios that require exploiting diverse, dynamic, large-scale collections of data","verifiable"),
("C-53","BFO は ISO/IEC 21838-2:2021 として標準化された上位オントロジーである","S-47","Basic Formal Ontology (BFO), which is an ontology that is conformant to the requirements specified for top-level ontologies in ISO/IEC 21838","verifiable"),
("C-54","Common Core Ontologies は、あらゆる領域に共通する汎用的な用語と関係を定義するオントロジー群である","S-48","suite of eleven ontologies that consist of logically well-defined generic terms and relations among them reflecting entities across all domains of interest","verifiable"),
("C-55","NIEM は公共部門と民間部門の組織間で情報を交換するための枠組みである","S-49","a framework for exchanging information between public and private sector organizations","verifiable"),
("C-56","FIBO は OWL で開発されたオントロジーである","S-50","FIBO is developed as an ontology in the Web Ontology Language (OWL)","verifiable"),
("C-57","Gene Ontology は生物学的知識の構造化され標準化された表現である","S-51","structured, standardized representation of biological knowledge","verifiable"),
("C-58","Gene Ontology の創設論文は 2000 年 5 月に Nature Genetics に掲載された","S-73","\"container-title\":[\"Nature Genetics\"]","verifiable"),
("C-59","SNOMED CT は多言語の臨床医療用語集である","S-52","multilingual clinical healthcare terminology","verifiable"),
("C-60","FHIR は HL7 が発行する医療データ交換の標準である","S-53","FHIR is a standard for health care data exchange, published by HL7","verifiable"),
("C-61","CFIHOS は産業施設の情報引き渡しのための標準化された仕様を目指している","S-54","practical standardised specifications for information handover that work for: anyone involved in making, operating, maintaining or decommissioning industrial facilities","verifiable"),
("C-62","アセット管理シェル (AAS) は各アセットをデジタルに表現する","S-55","Asset Administration Shell (AAS), which represents each asset digitally","verifiable"),
("C-63","ECLASS は製品マスタデータを業種・国・言語・組織を越えてデジタルに交換できるようにする","S-56","product master data can be exchanged digitally across all borders – across sectors, countries, languages and organizations","verifiable"),
("C-64","Industrial Ontologies Foundry はデジタル製造の全領域にわたるオープンな参照オントロジー群の作成を使命とする","S-57","create a set of core and open reference ontologies that spans the entire domain of digital manufacturing","verifiable"),
("C-65","OBO Foundry は生物科学のための相互運用可能なオントロジーをコミュニティで開発する","S-58","Community development of interoperable ontologies for the biological sciences","verifiable"),
("C-66","共通語彙基盤 (IMI) は、データに用いる用語の表記・意味・構造を統一することを目的とする","S-59","データに用いる様々な用語の表記、意味、構造を統一し","verifiable"),
("C-67","IDS インフォメーションモデルは IDS の基本概念を扱う RDFS/OWL オントロジーである","S-60","The Information Model is an RDFS/OWL-ontology covering the fundamental concepts of the","verifiable"),
("C-68","IDS インフォメーションモデルの GitHub リポジトリはアーカイブ済みである","S-61","\"archived\": true","verifiable"),
("C-69","データスペースプロトコル 2025-1 は JSON-LD 1.1 を用い、メッセージは JSON Schema で規範的に定義される","S-62","are normatively defined by a [[json-schema]]. This specification also uses JSON-LD 1.1","verifiable"),
("C-70","データスペースプロトコルのカタログプロトコルは DCAT と ODRL の語彙の属性を再利用する","S-63","reuses properties from the DCAT and ODRL vocabularies","verifiable"),
("C-71","Eclipse Foundation は 2025 年 12 月 2 日、ISO/IEC JTC1 の PAS 手続きで国際標準化に提出される 2 つのプロトコル仕様の公開を発表した","S-64","announced the release of two key protocol specifications that will be submitted for international standardisation through the ISO/IEC JTC1 Publicly Available Specification (PAS) process","verifiable"),
("C-72","欧州相互運用性フレームワークは相互運用性を法的、組織的、意味的、技術的の 4 層で整理する","S-65","four layers of interoperability: legal, organisational, semantic and technical","verifiable"),
("C-73","欧州相互運用性フレームワークは意味的相互運用性を、交換されるデータと情報の正確な形式と意味が当事者間のやり取りを通じて保たれ理解されることと説明する","S-65","Semantic interoperability ensures that the precise format and meaning of exchanged data and information is preserved and understood throughout exchanges between parties","verifiable"),
("C-74","DSSC ブループリントは、データモデルを語彙・オントロジー・アプリケーションプロファイル・スキーマ仕様を含むものと定義する","S-66","including vocabularies, ontologies, application profiles, schema specifications","verifiable"),
("C-75","ODS-RAM はデータ、トランザクション、アイデンティティ、セマンティクスの 4 レイヤで構成される","S-67","「④ セマンティクス（Semantics） 」の4つのレイヤで構成される","verifiable"),
("C-76","ODS-RAM のセマンティクスレイヤは、メタデータの提供によるセマンティクスおよびオントロジーの相互運用性を要求する","S-67","L4は、「 メタデータ（Metadata） 」をアクセス可能な形で提供することによる、セマンティクス及びオントロジーの相互運用性を要求する","verifiable"),
("C-77","IPA は ODS-RAM V2 を成果物として公開した","S-68","Open Data Spaces Reference Architecture Model (ODS-RAM) V2","verifiable"),
("C-78","Catena-X のアスペクトモデルは SAMM に準拠しなければならない","S-69","An Aspect Model must adhere to the Semantic Aspect Meta Model (SAMM) and be compliant with its validity rules.","verifiable"),
("C-79","SAMM は RDF と Turtle 構文で規定され、SHACL の検証規則を伴う","S-70","The Meta Model is specified using the Resource Description Format (RDF, [rdf11] ) and the Terse RDF Triple Language syntax (TTL, [turtle] ), together with validation rules in the Shapes Constraint Language","verifiable"),
("C-80","DCAT-AP は欧州でデータセットとデータサービスを記述するカタログ情報を共有するための DCAT プロファイルである","S-71","DCAT-AP is a DCAT profile for sharing information about Catalogues containing Datasets and Data Services descriptions in Europe","verifiable"),
("C-81","Gaia-X のクレデンシャルは、クレームを RDF で表現した W3C 検証可能クレデンシャルである","S-72","Gaia-X Credentials are W3C Verifiable Credentials with claims expressed in RDF.","verifiable"),
("C-82","Apache Incubator の記録では、Ossie のインキュベーション開始は 2026 年 6 月 22 日である","S-75","2026-06-22 Project enters incubation.","verifiable"),
("C-83","Apache Incubator のステータスページは Ossie を、業務指標・ディメンション・それらの関係を表すベンダ中立の形式を定義するオープン仕様と説明する","S-75","an open specification that defines a vendor-neutral format for expressing business metrics, dimensions, and their relationships","verifiable"),
("C-84","Microsoft は Power BI のデータセットというコンテンツ種別をセマンティックモデルに改称した","S-76","Microsoft has renamed the Power BI dataset content type to semantic model","verifiable"),
("C-85","IEC 63278-1:2023 は、アセットの標準化されたデジタル表現の構造を定義する","S-77","IEC 63278-1:2023 defines the structure of a standardized digital representation of an asset","verifiable"),
("C-86","schema.org は 2011 年 6 月 2 日付の記事で、Google、Bing、Yahoo! の取り組みとして発表された","S-78","a new initiative from Google, Bing and Yahoo! to create and support a common set of schemas for structured data markup on web pages","verifiable"),
("C-87","ISO/IEC DIS 26450（Eclipse Dataspace Protocol）は、各国標準化機関の写しによれば FDIS としての登録が承認された段階にある","S-79","DIS approved for registration as FDIS","verifiable"),
("C-88","IDS インフォメーションモデルの契約クラスは ODRL の Policy のサブクラスである","S-80","rdfs:subClassOf odrl:Policy","verifiable"),
("C-89","IDS インフォメーションモデルの Resource は DCAT-AP 1.1 の属性にもとづいて選定されている","S-81","Selection based on DCAT-AP 1.1 mandatory and recommended properties for dcat:Dataset","verifiable"),
("C-90","データスペースプロトコルでの DCAT と ODRL の再利用は、JSON Schema と JSON-LD コンテキストを通じて暗黙に行われる","S-63","This is done implicitly by the use of the JSON schemas and JSON-LD-contexts","verifiable"),
("C-91","DCAT 第 2 版は 2020 年 2 月 4 日に W3C 勧告となった","S-28","W3C Recommendation 04 February 2020","verifiable"),
("C-92","DCAT 第 3 版は 2024 年 8 月 22 日に W3C 勧告となった","S-29","W3C Recommendation 22 August 2024","verifiable"),
("C-93","DCAT-AP 3.0.1 は 2025 年 10 月 27 日付の SEMIC 勧告である","S-71","status SEMIC Recommendation published at 2025-10-27","verifiable"),
("C-94","Databricks の 2026 年 4 月 2 日付記事は、Unity Catalog Business Semantics の一般提供とオープンソース化を告知した","S-35","Announcing General Availability and Open Sourcing of Unity Catalog Business Semantics","verifiable"),
("C-95","Eclipse Foundation が提出を発表した 2 仕様の一つは Eclipse Dataspace Decentralised Claims Protocol である","S-64","Eclipse Dataspace Decentralised Claims Protocol","verifiable"),
("C-96","IMI は情報共有基盤（Infrastructure for Multilayer Interoperability）の略である","S-59","Infrastructure for Multilayer Interoperability","verifiable"),
("C-97","ODS-RAM は、意味に関するメタデータを、利用に必要な情報の意味についてユニークかつアクセス可能な形式で定義付けするよう求める","S-67","意味に関するメタデータは、データまたはサービスを利用するために必要な情報（入力/出力データ）の意味に関してユニークかつアクセス可能な形式で定義付けされなければならない","verifiable"),
("C-98","ODS のメタデータエクスチェンジ仕様は、情報モデルに RDF を、データモデルに JSON-LD 形式や Turtle 形式を採用する","S-82","情報モデルとしてRDF(Resource Description Framework)を採用し、データモデルとしてJSON-LD 形式やTurtle形式を","verifiable"),
("C-99","Apache Ossie のコア仕様では、1 つの JSON または YAML 文書が 1 つのセマンティックモデルを表す","S-83","Each JSON or YAML document represents exactly one semantic model.","verifiable"),
("C-100","Apache Ossie のコア仕様の版は 0.2.0.dev0 である","S-83","0.2.0.dev0","verifiable"),
("C-101","Apache Ossie のオントロジー仕様は、オントロジーを企業データの概念モデルと説明する","S-84","Ontologies are conceptual models of enterprise data that describe the enterprise in terms","verifiable"),
("C-102","ODS のメタデータエクスチェンジ仕様は、メタデータを RDF で表現することを求める","S-82","メタデータは、RDFで表現されなければならない","verifiable"),
("C-103","ODS のメタデータエクスチェンジ仕様は、メタデータを JSON-LD 形式で送受信することを原則とする","S-82","メタデータは JSON-LD 形式で送受信されることを原則とする","verifiable"),
("C-104","ODS-RAM の用語集は開世界仮説を、知識ベースにない情報を真でも偽でもない未知と見なす考え方と説明する","S-85","ある情報が知識ベースに存在しない場合、その情報は「真でも偽でもない（未知）」と見なす考え方","verifiable"),
("C-105","Apache Ossie のコア仕様では、データセットは物理的な表やビューを参照する","S-83","Reference to underlying physical table/view","verifiable"),
("C-106","ODS のメタデータエクスチェンジ仕様は、取得手段の一つに SPARQL を挙げる","S-82","SPARQL取得","verifiable"),
("C-107","デジタル庁の GIF は、データモデルを、データの構造や項目に加えてデータとデータの関係性を定義したものとする","S-86","データとデータの関係性を定義したもの","verifiable"),
("C-108","デジタル庁の GIF は、データ連携を行うシステムが標準化され参照可能なデータモデルを使う取り組みを重要とする","S-86","標準化され参照可能なデータモデルを使用するといった取組が重要です","verifiable"),
("C-109","GIF のコアデータモデルは、共通的に参照されるデータの基本的なデータ構造を定義したデータモデルである","S-87","それらの基本的なデータ構造を定義したデータモデルになります","verifiable"),
("C-110","IPA のガイドは、標準の語彙ではデータの意味が標準化されているため共通理解が容易だと述べる","S-88","データの意味が標準化されているので、データの共通理解が容易であり","verifiable"),
("C-111","IPA のガイドは、ラベルを統一する作業とコストを全ての参加者へ強制することは現実的ではないと述べる","S-88","全ての参加者へ強制することは現実的ではない","verifiable"),
("C-112","IPA のガイドは、同じ文脈で使われる「融資」と「貸付」を意味としてつなぐ手順を主に取り上げる","S-88","を意味としてつなぐ手順や表現方法である","verifiable"),
("C-113","ODS の SDK for Semantics には、ODS (Open Data Space) Ontology と題するファイルがある","S-89","ODS (Open Data Space) Ontology","verifiable"),
("C-114","ODS オントロジーは、データスペースにおけるデータ交換サービスとエンドポイントを定義する","S-89","ODSオントロジーは、データスペースにおけるデータ交換サービスとエンドポイントを定義します。","verifiable"),
("C-115","ODS オントロジーは OWL のオントロジーとして宣言され、ods:DataExchangeService を OWL のクラスとして定義する","S-89","ods:DataExchangeService a owl:Class","verifiable"),
("C-116","ODS の SDK for Semantics は、Web サービスの RDF 定義に、Eclipse ESMF の SAMM をベースとした定義を採用する","S-90","をベースとしたセマンティックな定義を採用している","verifiable"),
("C-117","ODS の SDK for Semantics は、SAMM に REST API の呼び出し方を定義する手段がないため、W3C 標準の語彙を組み合わせて API 定義を拡張する","S-90","を組み合わせてAPI定義を拡張している","verifiable"),
("C-118","ODS のサンプルの RDF サーバーは、Apache Jena Fuseki に対して SPARQL クエリを実行する","S-91","RDFサーバーはローカルのApache Jena Fusekiエンドポイントに対してSPARQLクエリを実行するためのREST APIを提供します。","verifiable"),
("C-119","ODS のサンプルには、ドローン航路の概念を OWL のクラスとして定義したオントロジーがある","S-92",":Uasl rdf:type owl:Class","verifiable"),
("C-120","ODS のチャットサーバは、SAMM アスペクトモデルと API 定義から MCP ツールを生成する","S-93","SAMMアスペクトモデルとAPI定義（TTL形式）からMCPツールを生成します。","verifiable"),
("C-121","ODS を主導する中立的な組織は IPA のデジタルアーキテクチャ・デザインセンター（DADC）である","S-94","serves as the neutral body leading ODS","verifiable"),
("C-122","UASL は Unmanned Aircraft Systems Lines の略である","S-94","UASL: Unmanned Aircraft Systems Lines","verifiable"),
("C-123","ODS の分散カタログは、複数のドメインアプリケーションが公開する SPARQL エンドポイントから RDF データを収集する","S-95","複数のドメインアプリケーションが公開するSPARQLエンドポイントからRDFデータを収集・格納し","verifiable"),
("C-124","ODS オントロジーのファイルは owl:Ontology を宣言する","S-89","a owl:Ontology","verifiable"),
("C-125","Palantir は、既存のデータ源をオブジェクト、プロパティ、リンクに対応づけることで、組織の意味を定義すると説明する","S-42","Defining the semantics of your organization happens by mapping existing datasources into objects, properties, and links in the Ontology.","verifiable"),
("C-126","Palantir のインターフェースは、オブジェクト型の形と能力を記述する型である","S-42","An interface is an Ontology type that describes the shape of an object type and its capabilities.","verifiable"),
("C-127","Palantir の必須プロパティは、値を持たなければならないプロパティである","S-96","Required properties are object type properties that must have a value.","verifiable"),
("C-128","Palantir の値型は、検証の制約を伴う、フィールド型の意味的なラッパーである","S-97","Value types are semantic wrappers around a field type that include metadata and constraints","verifiable"),
("C-129","Palantir の複数データソースのオブジェクト型は、複数のデータソースを背後に持つ","S-98","A multi-datasource object type (MDO) is backed by multiple datasources in the Ontology","verifiable"),
("C-130","Palantir の複数データソースのオブジェクト型では、主キーがすべての入力データソースに存在しなければならない","S-98","which must exist in every input datasource to join all datasources","verifiable"),
("C-131","Palantir の共有プロパティは、メタデータを共有するが、背後のオブジェクトのデータは共有しない","S-99","While property metadata is shared across objects, the underlying object data is not.","verifiable"),
("C-132","Palantir のインターフェースは、別のインターフェースを拡張して、そのプロパティを継承する子を作れる","S-100","you can extend an interface to create a child interface that inherits the properties of the original interface","verifiable"),
("C-133","Palantir の派生プロパティは、他のプロパティやリンクの値にもとづいて実行時に計算される","S-101","Derived properties are properties that are calculated at runtime based on the values of other properties or links on objects.","verifiable"),
("C-134","Palantir の関数が対応する言語は TypeScript と Python である","S-102","The languages supported by functions are TypeScript","verifiable"),
("C-135","Palantir は、Foundry のデータ型が RDF、OWL、XSD の類似の概念に着想を得ていると述べる","S-103","Data types in Foundry are inspired by similar concepts in RDF","verifiable"),
("C-136","Palantir は、自社の Ontology はセマンティックレイヤではないと述べる","S-104","The Ontology is not a","verifiable"),
("C-137","Palantir の Ontology のスキーマ定義は JSON ファイルに保存され、書き出しと取り込みができる","S-105","Ontology schema definitions are stored in a JSON file","verifiable"),
("C-138","Palantir は、書き出した JSON のスキーマは変わりうるので依存すべきでないと述べる","S-105","You should not depend on the exported JSON schema as it may change over time.","verifiable"),
("C-139","Apache Ossie のロードマップは、オントロジーで意味を定義する例として Palantir と Goldman Sachs Legend を挙げる","S-106","Many semantic representations (e.g., Palantir, Goldman Sachs Legend) use ontologies to define meaning","verifiable"),
("C-140","Apache Ossie のロードマップは、Ossie は構造的な相互運用性を解決するが、概念的な相互運用性はまだ解決していないと述べる","S-106","but it does not yet solve conceptual interoperability","verifiable"),
("C-141","Business Objects の特許は、利用者が関係構造や SQL を知らずに関係データベースへ問い合わせられるようにする技術を記述する","S-107","without knowing the relational structure or the structure query language (SQL)","verifiable"),
("C-142","Business Objects の特許の優先日は 1991 年 11 月 27 日である","S-107","1991-11-27","verifiable"),
("C-143","Stancil は指標レイヤを、すべての指標の計算方法を一か所で決める場所と説明する","S-108","the metrics layer is a centralized clearing house for how all metrics are calculated","verifiable"),
("C-144","dbt Labs は、指標の定義を BI の層からモデリングの層へ移すことで、どのツールでも同じ定義を使えると説明する","S-111","different business units are working from the same metric definitions, regardless of their tool of choice","verifiable"),
("C-145","Snowflake の発表文は、OSI の狙いを AI と BI のアプリケーションで一貫した業務ロジックを確保することと述べる","S-30","ensuring consistent business logic across AI and business intelligence (BI) applications","verifiable"),
("C-146","Apache Ossie の README は、同じ KPI がツールごとに違う定義になっていることを問題に挙げる","S-34","the same KPI defined differently across tools","verifiable"),
("C-147","Hogan は、セマンティックウェブの標準が長く複雑で、新しい利用者を引きつける障壁になるという批判を紹介する","S-109","This creates a major barrier for attracting new adopters.","verifiable"),
("C-148","Hogan は同じ箇所で、SQL の標準も大部であるという反論を併記する","S-109","one should not overlook the SQL:2016 standard","verifiable"),
("C-149","Anadiotis は、Data Cube の語彙や指標のオントロジーは存在するが、セマンティックレイヤの界隈では使われていないようだと書く","S-110","A Data Cube vocabulary and a metric ontology do exist, but it doesn","verifiable"),
("C-150","Apache Ossie のオントロジー仕様は、概念や関係を既存の RDF や OWL の語彙の定義に関連づけられるようにしている","S-84","for instance a class or property in an existing RDF or OWL vocabulary","verifiable"),
("C-151","ODS のコンセプトペーパーは、Ontology Product で開世界仮説を前提とすると述べる","S-112","Product で OWA を前提としながら、Data","verifiable"),
("C-152","ODS のコンセプトペーパーは、Data Product で閉世界仮説を選択的に導入する二層の構造を取ると述べる","S-112","Product で CWA を選択的に導入するという二層","verifiable"),
("C-153","ODS のコンセプトペーパーは、データモデルから情報モデルを明確に分離すると述べる","S-112","」を明確に分離す","verifiable"),
("C-154","ODS のコンセプトペーパーは、OWL によって妥当性や排他性といった制約を定義すると述べる","S-112","Ontology Language（OWL）により妥当性や排他","verifiable"),
("C-155","ODS のコンセプトペーパーは、閉世界仮説の強制は Open Dataspaces の発想と相いれないと述べる","S-112","Dataspaces の発想とは相いれない。","verifiable"),
("C-156","ODS のコンセプトペーパーは、意味を後から付与するスキーマフレキシブルという技術指針を示す","S-112","味を後から付与する「スキーマフレキシブル","verifiable"),
("C-157","ODS のコンセプトペーパーは、意味の所在をコードから論理体系へ移す設計思想だと述べる","S-112","意味の所在をコードから論理体系へ移すという設","verifiable"),
("C-158","ODS のコンセプトペーパーは、開放性を維持しながら選択的な厳格性を実現できる点を強みに挙げる","S-112","維持しながら、選択的な厳格性を実現できる点で","verifiable"),
("C-159","ODS のコンセプトペーパーは、第一の柱を Ontology and Semantic Interoperability（OSI）と呼ぶ","S-112","Ontology and Semantic Interoperability（OSI）","verifiable"),
("C-160","データスペースプロトコルの 0.8 版と 2024-1 版は、IDSA の管理のもとで開発され公開された","S-113","have been developed and released under the governance of the","verifiable"),
("C-161","データスペースプロトコルの 2024-1 版は、IDSA から Eclipse のプロジェクトへの最初の寄贈にあたる","S-113","marks the initial contribution to the","verifiable"),
("C-162","IDS-RAM 4.0 は、宣言的表現である IDS 語彙を、インフォメーションモデルの唯一の規範的な仕様とする","S-114","the Declarative Representation (IDS Vocabulary) is the only normative specification of the Information Model","verifiable"),
("C-163","データスペースプロトコル 2025-1 は、独自の名前空間 dspace を定義する","S-115","https://w3id.org/dspace/2025/1/","verifiable"),
("C-164","データスペースプロトコル 2024-1 は、版の情報を返すデータが JSON Schema と SHACL のシェイプの両方に従うことを求めた","S-116","must comply to the [JSON Schema](schema/version-schema.json) and the [SHACL Shape](shape/version-shape.ttl)","verifiable"),
("C-165","データスペースプロトコルの最初期の版（0.8）は、データ資産を DCAT のカタログとして、利用制御を ODRL のポリシーとして表すとした","S-117","usage control is expressed as [ODRL Policies]","verifiable"),
("C-166","JSON Schema を規範とする提案は、当時の仕様がメッセージ型を規範的に定めるスキーマ技術を使っていないことを問題に挙げた","S-118","use a schema technology to define message types","verifiable"),
("C-167","JSON Schema を規範とする提案は、JSON-LD の処理を任意にすることを提案した","S-118","make JSON-LD processing optional","verifiable"),
("C-168","Apache Ossie のコア仕様は、指標を、合計、平均、比率のような計算を表す、業務データに対する量的な尺度と説明する","S-83","Quantitative measures defined on business data, representing key calculations like sums, averages, ratios, etc.","verifiable"),
("C-169","Apache Ossie のコア仕様は、フィールドを、グループ分け、絞り込み、指標の式に使える行ごとの属性と説明する","S-83","Fields represent row-level attributes that can be used for grouping, filtering, and in metric expressions.","verifiable"),
("C-170","Ogden と Richards は、記号と対象は直接にはつながっていないと述べる","S-119","Symbol and Referent, that is to say, are not connected directly","verifiable"),
("C-171","Uschold と Gruninger は、連続体に沿って進むほど、指定される意味の量と形式性の度合いが増すと述べる","S-120","the amount of meaning specified and the degree of formality increases","verifiable"),
("C-172","McGuinness は、オントロジーを仕様の詳しさの連続体として示す図をオントロジー・スペクトラムと呼ぶ","S-121","An Ontology Spectrum","verifiable"),
("C-173","RFC 3444 は、データモデルは情報モデルより低い抽象度で定義され、多くの詳細を含むと述べる","S-122","DMs, conversely, are defined at a lower level of abstraction and include many details.","verifiable"),
("C-174","RFC 3444 は、一つの情報モデルから複数のデータモデルを導けると述べる","S-122","multiple DMs can be derived from a single IM","verifiable"),
("C-175","W3C は、語彙と呼ばれるものとオントロジーと呼ばれるものの間に明確な区分はないと述べる","S-123","There is no clear division between what is referred to as","verifiable"),
("C-176","Wikidata のデータモデルの図は、Wikimedia Commons で公開されている","S-124","Datamodel in Wikidata","verifiable"),
("C-177","Palantir は、オントロジーを世界の分類と説明する","S-125","An Ontology is a categorization of the world.","verifiable"),
("C-178","欧州相互運用性フレームワークの相互運用性モデルは、4 層に加えて、4 層を横断する要素と、背景となる層を持つ","S-65","a background layer","verifiable"),
("C-179","欧州相互運用性フレームワークの冊子は、出典を示せば複製を認めると記している","S-65","Reproduction is authorised provided the source is acknowledged.","verifiable"),
("C-180","Uschold と Gruninger は、連続体に沿って進むほど自動推論への支援も増すと述べる","S-120","there is also increasing support for automated reasoning","verifiable"),
("C-181","Apache Ossie のブログ記事は、人の分析者や AI エージェントが、どの定義が正しいかを推測しなければならないべきではないと述べる","S-33","they shouldn't have to guess which definition is correct","verifiable"),
("C-182","Ogden と Richards の図の頂点は、SYMBOL、THOUGHT OR REFERENCE、REFERENT である","S-119","THOUGHT OR REFERENCE","verifiable"),
("C-183","データスペースプロトコル 2024-1 は、すべてのメッセージを JSON-LD のコンパクト形式で直列化することを求めた","S-126","All messages must be serialized in JSON-LD compact form","verifiable"),
("C-184","IDS-RAM 4.0 は、デジタル資源の記述を SHACL のシェイプで検証できるとする","S-114","validated against SHACL shapes","verifiable"),
("C-185","MCP は、AI アプリケーションを外部のシステムにつなぐためのオープンソースの標準である","S-127","MCP (Model Context Protocol) is an open-source standard for connecting AI applications to external systems.","verifiable"),
("C-186","Palantir の主キーは、オブジェクト型の各インスタンスの一意な識別子として働くプロパティである","S-128","acts as a unique identifier for each instance of an object type","verifiable"),
("C-187","SNOMED CT の中核の構成要素は、概念、記述、関係である","S-52","The core component types in SNOMED CT are concepts, descriptions and relationships.","verifiable"),
("C-188","2026 年 4 月の更新は、オントロジーの表現を扱うワーキンググループを挙げる","S-32","Ontology Representation","verifiable"),
("C-189","Google Cloud は OKF を、LLM ウィキのパターンを持ち運べて相互運用できる形式として定めたオープン仕様と説明する","S-131","an open specification that formalizes the LLM-wiki pattern into a portable, interoperable format","verifiable"),
("C-190","OKF 0.1 版は、知識を YAML の前書きつき Markdown ファイルのディレクトリで表す","S-131","OKF v0.1 represents knowledge as a directory of markdown files with YAML frontmatter","verifiable"),
("C-191","OKF の発表記事の著者は、データ分析と BigQuery の技術リードである","S-131","Tech Lead, Data Analytics","verifiable"),
("C-192","OKF の仕様は、OKF を、組織をまたいで交換されることを想定した形式と説明する","S-129","exchanged across organizations","verifiable"),
("C-193","OKF の前書きで常に必須なのは type だけである","S-129","is the only always-required key","verifiable"),
("C-194","OKF の type の値は、中央に登録されない","S-129","registered centrally","verifiable"),
("C-195","OKF では、関係の種類はリンクそのものではなく周りの文章が伝える","S-129","surrounding prose, not by the link itself","verifiable"),
("C-196","OKF の仕様は、概念の型の固定の分類を定めることを、目的としないものに挙げる","S-129","Defining a fixed taxonomy of concept types.","verifiable"),
("C-197","OKF の仕様は、今後の課題にセマンティックレイヤのテンプレート（Looker、dbt）を挙げる","S-129","Semantic-layer templates (Looker, dbt)","verifiable"),
("C-198","OKF の README は、OKF が表すものをカタログの知識と呼ぶ","S-130","OKF represents catalog knowledge as plain markdown files with YAML","verifiable"),
("C-199","OKF の README は、既存のカタログからの書き出しを作り手の一つに挙げる","S-130","existing catalogs (Dataplex, Unity Catalog, Collibra","verifiable"),
("C-200","OKF 0.2 版は、0.1 版と同じく、最小限の決まりだけを定める形式のままであると記事は述べる","S-132","while the format remains as minimally opinionated as v0.1","verifiable"),
("C-201","記事は、検証つきの計算が、Looker や AtScale などのセマンティックモデルの呼び出しにも対応しうると述べる","S-132","Attested computations can correspond to invoking semantic models (in Looker, AtScale, or other systems)","verifiable"),
("C-202","OKF 0.2 版は、来歴、信頼、ライフサイクル、検証を第一級の項目にした","S-129","OKF v0.2 makes provenance, trust, lifecycle, and attestation first-class","verifiable"),
("C-203","OKF の仕様は、type の値の例に BigQuery のテーブルや指標を挙げる","S-129","`BigQuery Table`, `BigQuery Dataset`, `API Endpoint`, `Metric`","verifiable"),
("C-204","OKF の resource は、概念が記述する資産を一意に識別する URI である","S-129","A URI that uniquely identifies the underlying asset","verifiable"),
("C-205","OKF のリンクは、グラフを作る側では種類のない有向の辺として扱われるのが普通とされる","S-129","view typically treat all links as directed edges of an untyped","verifiable"),
("C-206","OKF の適合の条件は、すべての前書きに空でない type があることを含む","S-129","Every frontmatter block contains a non-empty `type` field.","verifiable"),
("C-207","OKF では、ディレクトリの構造が暗黙の親子関係を表す","S-129","the implicit parent/child hierarchy","verifiable"),
("C-208","W3C の勧告は、形式的な意味の水準を、データと、最もありそうな用途の両方に合うように選ぶよう勧める","S-133","Opt for a level of formal semantics that fits both data and the most likely applications.","verifiable"),
("C-209","W3C の勧告は、複雑な語彙は作るのにも理解するのにも手間がかかり、再利用の妨げになりうると述べる","S-133","such complex vocabularies require more effort to produce and understand","verifiable"),
("C-210","W3C の勧告は、共有された語彙、できれば標準化された語彙の用語を使うよう勧める","S-133","Use terms from shared vocabularies, preferably standardized ones, to encode data and metadata.","verifiable"),
]
esc=lambda s:s.replace("|","\\|")
out=["# 出典台帳（Source Register / Claim Ledger）","","- 作成日: 2026-10-02（S-86 から S-125 は 2026-10-03、S-126 以降は 2026-10-04 に取得）","- 生成元: `build_ledger.py`（追記のみ。行を消さない）","","## Source Register","","| ID | Source | URL | Tier | Accessed | Retriever |","|---|---|---|---|---|---|"]
acc=lambda i: "2026-10-02" if int(i[2:])<=85 else ("2026-10-03" if int(i[2:])<=125 else "2026-10-04")
for i,n,u,t,q in S: out.append(f"| {i} | {esc(n)} | {u} | {t} | {acc(i)} | {q} |")
out+=["","## Claim Ledger","","| ID | Claim | Source | Span (verbatim) | Kind | Status |","|---|---|---|---|---|---|"]
import json,os
ST=json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),"status.json")))
for i,c,s,sp,k in C: out.append(f"| {i} | {esc(c)} | {s} | \"{esc(sp)}\" | {k} | {ST.get(i,'Unverified')} |")
out+=open(os.path.join(os.path.dirname(os.path.abspath(__file__)),"ledger-tail.md")).read().split("\n")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)),"ledger.md"),"w").write("\n".join(out)+"\n")
print(len(S),len(C))
